# Generated by Django 3.0.8 on 2020-09-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doclocker_app', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
